[project]
name = "wxcreategroups"
version = "0.1.0"
readme = "README.md"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.2.3",
    "sphinx>=8.2.3",
    "sphinx-rtd-theme>=3.0.2",
    "wxpython>=4.2.2",
]
